# Generated by Django 5.2.17 on 2026-09-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_campaign_contactmessage_donation_testimonial_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='transaction_id',
            new_name='razorpay_order_id',
        ),
        migrations.AddField(
            model_name='donation',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='donation',
            name='razorpay_signature',
            field=models.TextField(blank=True),
        ),
    ]
